package o0OOo00;

import android.os.Parcel;
import com.google.android.gms.ads.RequestConfiguration;
import kotlin.Metadata;
import o0OO0o.o0O0O0o0;
import o0OO0o.o0O0oo0o;
import o0OOOOO0.o0ooO;
import org.jetbrains.annotations.NotNull;
@Metadata(bv = {}, d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0005\n\u0002\u0010\u0011\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J#\u0010\b\u001a\u00020\u0007*\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\u0006\u001a\u00020\u0005H&¢\u0006\u0004\b\b\u0010\tJ\u0017\u0010\n\u001a\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u0003H&¢\u0006\u0004\b\n\u0010\u000bJ\u001d\u0010\u000e\u001a\b\u0012\u0004\u0012\u00028\u00000\r2\u0006\u0010\f\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u000e\u0010\u000f¨\u0006\u0010"}, d2 = {"Lo0OOo00/o00oOo00;", RequestConfiguration.MAX_AD_CONTENT_RATING_T, "", "Landroid/os/Parcel;", "parcel", "", "flags", "Lo0OO0o/oO0Ooooo;", "o00oOOo0", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", o0OO000o.o00oOOoO.f12961o00oOo00, "(Landroid/os/Parcel;)Ljava/lang/Object;", "size", "", "newArray", "(I)[Ljava/lang/Object;", "kotlin-android-extensions-runtime"}, k = 1, mv = {1, 4, 1})
/* loaded from: classes3.dex */
public interface o00oOo00<T> {

    @o0O0oo0o(bv = {1, 0, 3}, k = 3, mv = {1, 4, 1}, xi = 48)
    /* loaded from: classes3.dex */
    public static final class o00oOOo0 {
        @NotNull
        public static <T> T[] o00oOOo0(@NotNull o00oOo00<T> o00ooo002, int i) {
            o0ooO.o00oo0O0(o00ooo002, "this");
            throw new o0O0O0o0("Generated by Android Extensions automatically");
        }
    }

    @NotNull
    T[] newArray(int i);

    void o00oOOo0(T t, @NotNull Parcel parcel, int i);

    T o00oOOoO(@NotNull Parcel parcel);
}
